name: "Validate Gradle Wrapper"

on:
  workflow_dispatch

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
